name: 'Setup Python with pip'
description: 'Setup Python environment with pip package manager for pyproject.toml projects'

inputs:
  python-version:
    description: 'Python version to install, default is 3.12'
    required: false
    default: '3.12'
  cache:
    description: 'Cache packages dependencies (pip, pipenv, poetry), if empty no caching is performed, default is empty'
    required: false
    default: ''
  install-groups:
    description: 'examples: "groups: dev test, extras: aws viz" or "groups: dev" or "extras: aws viz". Leave empty to install only core dependencies. default is empty'
    required: false
    default: ''
  architecture:
    description: 'Target architecture for Python to use (x64, x86), default is x64'
    required: false
    default: 'x64'


runs:
  using: 'composite'
  steps:
    - name: Validate cache requirements
      if: ${{ inputs.cache != '' }}
      shell: bash
      run: |
        echo "::group::Validating cache requirements"
        if [ ! -f pyproject.toml ] && [ ! -f requirements.txt ]; then
          echo "::error::Cache is enabled (cache='${{ inputs.cache }}') but no pyproject.toml or requirements.txt found."
          echo "::error::Either create a pyproject.toml/requirements.txt file or set cache: '' to disable caching."
          exit 1
        fi
        echo "Cache validation passed - found dependency file"
        echo "::endgroup::"

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.python-version }}
        cache: ${{ inputs.cache }}
        architecture: ${{ inputs.architecture }}

    - name: Upgrade pip
      shell: bash
      run: |
        echo "::group::Upgrading pip"
        python -m pip install --upgrade pip
        echo "::endgroup::"

    - name: Install dependencies
      shell: bash
      run: |
        echo "::group::Installing dependencies"
        if [ -f pyproject.toml ]; then
          echo "Found pyproject.toml, installing package..."
          
          # Check if install-groups are specified
          if [ -n "${{ inputs.install-groups }}" ]; then
            echo "Processing install-groups: ${{ inputs.install-groups }}"
            
            input_str="${{ inputs.install-groups }}"
            dependency_groups=()
            optional_deps=()
            
            # Extract groups section if present
            if [[ "$input_str" =~ groups:[[:space:]]*([^,]*)(,|$) ]]; then
              groups_part="${BASH_REMATCH[1]}"
              # Remove leading/trailing whitespace and split on spaces
              groups_part=$(echo "$groups_part" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
              if [[ -n "$groups_part" ]]; then
                IFS=' ' read -r -a group_names <<< "$groups_part"
                for group in "${group_names[@]}"; do
                  group=$(echo "$group" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
                  if [[ -n "$group" ]]; then
                    dependency_groups+=("$group")
                    echo "  - Found dependency group: $group"
                  fi
                done
              fi
            fi
            
            # Extract extras section if present
            if [[ "$input_str" =~ extras:[[:space:]]*([^,]*)(,|$) ]]; then
              extras_part="${BASH_REMATCH[1]}"
              # Remove leading/trailing whitespace and split on spaces
              extras_part=$(echo "$extras_part" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
              if [[ -n "$extras_part" ]]; then
                IFS=' ' read -r -a extra_names <<< "$extras_part"
                for extra in "${extra_names[@]}"; do
                  extra=$(echo "$extra" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
                  if [[ -n "$extra" ]]; then
                    optional_deps+=("$extra")
                    echo "  - Found optional dependency (extra): $extra"
                  fi
                done
              fi
            fi
            
            # Check if neither groups nor extras were found - might be old format
            if [ ${#dependency_groups[@]} -eq 0 ] && [ ${#optional_deps[@]} -eq 0 ]; then
              echo "::warning::No 'groups:' or 'extras:' sections found. Please use format: 'groups: name1 name2, extras: extra1 extra2'"
            fi

            # Summary of what will be installed
            echo ""
            echo "=== Installation Summary ==="
            if [ ${#dependency_groups[@]} -gt 0 ]; then
              echo "✓ Dependency groups will be installed: ${dependency_groups[*]}"
            else
              echo "✗ No dependency groups specified"
            fi
            if [ ${#optional_deps[@]} -gt 0 ]; then
              echo "✓ Optional dependencies (extras) will be installed: ${optional_deps[*]}"
            else
              echo "✗ No optional dependencies specified"
            fi
            echo "✓ Core dependencies will always be installed"
            echo "=========================="
            echo ""

            # Install the package first
            if [ ${#optional_deps[@]} -gt 0 ]; then
              # Build comma-separated list of optional dependencies for pip install .[extras]
              extras_list=""
              for extra in "${optional_deps[@]}"; do
                if [[ -z "$extras_list" ]]; then
                  extras_list="$extra"
                else
                  extras_list="$extras_list,$extra"
                fi
              done
              install_cmd="pip install .[$extras_list]"
              echo "Installing package with optional dependencies: $install_cmd"
              eval "$install_cmd"
            else
              echo "Installing package without optional dependencies..."
              pip install .
            fi

            # Install dependency groups if any (requires pip with PEP 735 support)
            if [ ${#dependency_groups[@]} -gt 0 ]; then
              # Build command with multiple --group flags
              dep_groups_cmd="pip install ."
              for group in "${dependency_groups[@]}"; do
                dep_groups_cmd="$dep_groups_cmd --group $group"
              done
              
              # Check if pip supports --group (PEP 735)
              if pip install --help | grep -q "\-\-group"; then
                echo "Installing dependency groups: $dep_groups_cmd"
                eval "$dep_groups_cmd"
              else
                groups_list=$(IFS=,; echo "${dependency_groups[*]}")
                pip_version=$(pip --version | awk '{print $2}')
                echo "::warning::pip version $pip_version does not support --group flag (PEP 735). Dependency groups will be ignored: $groups_list"
                echo "::warning::Please upgrade pip to version >= 24.2 or consider using the uv action instead."
                echo "::warning::Suggested workaround: Specify version: '24.2' or version: 'latest' in the action inputs."
              fi
            fi
          else
            echo "Installing package without optional groups or extras..."
            pip install .
          fi
        else
          echo "No pyproject.toml found - skipping package installation"
        fi
        echo "::endgroup::"

    - name: List installed packages
      shell: bash
      run: |
        echo "::group::Installed packages summary"
        pip list
        echo "::endgroup::"