name: 'Setup Python with pixi'
description: 'Setup Python environment with pixi package manager and install dependencies'

inputs:
  environments:
    description: 'Pixi environments to install (e.g., "py311", "py312 py313")'
    required: false
    default: 'default'
  activate-environment:
    description: 'Environment to activate after installation'
    required: false
    default: 'default'
  cache:
    description: 'Whether to enable caching of pixi environments'
    required: false
    default: 'false'
  verify-lock:
    description: 'Whether to verify the lock file is up to date'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Validate lock file exists
      shell: bash
      run: |
        if [ ! -f "pixi.lock" ]; then
          echo "::error::❌ pixi.lock file does not exist!"
          echo "::error::To fix this issue:"
          echo "::error:: Run 'pixi install' locally to generate pixi.lock and commit it to your repository"
          echo "::error::This action requires a committed lock file and will never generate it in CI."
          exit 1
        fi
        echo "✓ Lock file exists"

    - name: Setup pixi (with cache)
      if: inputs.cache == 'true'
      uses: prefix-dev/setup-pixi@fef5c9568ca6c4ff7707bf840ab0692ba3f08293 # v0.9.0
      with:
        environments: ${{ inputs.environments }}
        activate-environment: ${{ inputs.activate-environment }}
        pixi-version: v0.49.0
        cache: true
        cache-key: pixi-${{ hashFiles('pixi.lock') }}
        cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
        locked: ${{ inputs.verify-lock == 'true' }}
        frozen: ${{ inputs.verify-lock != 'true' }}

    - name: Setup pixi (without cache)
      if: inputs.cache != 'true'
      uses: prefix-dev/setup-pixi@fef5c9568ca6c4ff7707bf840ab0692ba3f08293 # v0.9.0
      with:
        environments: ${{ inputs.environments }}
        activate-environment: ${{ inputs.activate-environment }}
        pixi-version: v0.49.0
        cache: false
        locked: ${{ inputs.verify-lock == 'true' }}
        frozen: ${{ inputs.verify-lock != 'true' }}

    - name: List environment info
      shell: bash
      run: |
        echo "::group::Pixi environment information"
        echo "Active environment: ${{ inputs.activate-environment }}"
        echo "Available environments:"
        pixi info
        echo "::endgroup::"

    - name: List installed packages
      shell: bash
      run: |
        echo "::group::Installed packages summary"
        pixi list -e ${{ inputs.activate-environment }}
        echo "::endgroup::"