name: 'Setup Python with pixi'
description: 'Setup Python environment with pixi package manager and install dependencies'

inputs:
  environments:
    description: 'Pixi environments to install (e.g., "py311", "py312 py313")'
    required: false
    default: 'default'
  activate-environment:
    description: 'Environment to activate after installation'
    required: false
    default: 'default'
  verify-lock:
    description: 'Whether to verify the lock file is up to date'
    required: false
    default: 'true'
  cache:
    description: 'Whether to enable caching of pixi environments'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Setup pixi
      uses: prefix-dev/setup-pixi@fef5c9568ca6c4ff7707bf840ab0692ba3f08293 # v0.9.0
      with:
        environments: ${{ inputs.environments }}
        activate-environment: ${{ inputs.activate-environment }}
        pixi-version: v0.49.0
        cache: ${{ inputs.cache == 'true' }}
        cache-key: pixi-${{ hashFiles('pixi.lock') }}
        cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}

    - name: Verify lock file is up to date
      if: inputs.verify-lock == 'true'
      shell: bash
      run: |
        echo "::group::Verifying pixi.lock file is up to date"
        output=$(pixi lock 2>&1)
          echo "$output"
          if echo "$output" | grep -q "Lock-file was already up-to-date"; then
            echo "✓ Lock file is up-to-date"
          else
            echo "✗ Lock file was out of sync and has been updated"
            echo "Please run 'pixi lock' locally and commit the changes"
            exit 1
          fi
        echo "::endgroup::"

    - name: List environment info
      shell: bash
      run: |
        echo "::group::Pixi environment information"
        echo "Active environment: ${{ inputs.activate-environment }}"
        echo "Available environments:"
        pixi info
        echo "::endgroup::"

    - name: List installed packages
      shell: bash
      run: |
        echo "::group::Installed packages summary"
        pixi list -e ${{ inputs.activate-environment }}
        echo "::endgroup::"