name: 'Install pixi and generate lock file'
description: 'Installs pixi CLI and generates pixi.lock from pyproject.toml for testing purposes'

inputs:
  pixi-version:
    description: 'Version of pixi to install'
    required: false
    default: 'v0.49.0'

runs:
  using: 'composite'
  steps:
    - name: Install pixi
      uses: prefix-dev/setup-pixi@fef5c9568ca6c4ff7707bf840ab0692ba3f08293 # v0.9.0
      with:
        pixi-version: ${{ inputs.pixi-version }}
        run-install: false

    - name: Generate lock file
      shell: bash
      run: pixi install

