name: 'Setup Python with uv'
description: 'Setup Python environment with uv package manager and install dependencies'

inputs:
  python-version:
    description: 'Python version to install'
    required: false
    default: '3.12'
  install-groups:
    description: 'uv sync groups to install (e.g., "dev", "dev docs"). Leave empty to install only core dependencies.'
    required: false
    default: ''
  verify-lock:
    description: 'Whether to verify the lock file is up to date'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true
        cache-dependency-glob: uv.lock

    - name: Verify lock file is up to date
      if: inputs.verify-lock == 'true'
      shell: bash
      run: |
        echo "::group::Verifying uv.lock file is up to date"
        uv lock --check
        echo "::endgroup::"

    - name: Install Dependencies
      shell: bash
      run: |
        echo "::group::Preparing uv sync command"

        # Start with frozen flag
        args=("--frozen")

        # Check if install-groups is provided
        if [[ -n "${{ inputs.install-groups }}" ]]; then
          echo "Installing with groups: ${{ inputs.install-groups }}"

          # Split groups on space and comma
          IFS=' ,' read -r -a groups <<< "${{ inputs.install-groups }}"

          for group in "${groups[@]}"; do
            # Remove leading/trailing whitespace
            group=$(echo "$group" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
            if [[ -n "$group" ]]; then
              args+=("--group" "$group")
            fi
          done
        else
          echo "Installing core dependencies only (no optional groups)"
          # Explicitly exclude all groups when install-groups is empty
          args+=("--no-dev")
        fi

        echo "Running: uv sync ${args[*]}"
        echo "::endgroup::"

        echo "::group::Installing dependencies with uv"
        uv sync "${args[@]}"
        echo "::endgroup::"

    - name: List environment contents
      shell: bash
      run: |
        echo "::group::Installed packages summary"
        uv pip list
        echo "::endgroup::"